-- Script de creación de tablas - Todo en español
-- Sistema de Gestión Escolar

CREATE TABLE "pais" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "estado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "pais_id" bigint,
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "municipio" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "estado_id" bigint,
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "parroquia" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "municipio_id" bigint,
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "rol" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50),
  "descripcion" text,
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "permisos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50),
  "descripcion" text,
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "personal" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cedula" varchar(20) UNIQUE,
  "nombre" varchar(100),
  "apellido" varchar(100),
  "rol_id" bigint,
  "telefono" varchar(20),
  "email" varchar(100),
  "fecha_nacimiento" timestamp,
  "direccion" varchar(30),
  "parroquia_id" bigint,
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "estado_estudiante" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(100),
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "brigada" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "brigada_docente_fecha" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brigada_id" bigint,
  "fecha_inicio" date,
  "personal_id" bigint,
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "representante" (
  "cedula" varchar(20) UNIQUE PRIMARY KEY,
  "nombre" varchar(100),
  "apellido" varchar(100),
  "telefono" varchar(20),
  "email" varchar(100),
  "estado_civil" varchar(20),
  "profesion" varchar(100),
  "fecha_nacimiento" timestamp,
  "telefono_casa" varchar(20),
  "direccion_habitacion" varchar(50),
  "lugar_trabajo" varchar(50),
  "telefono_trabajo" varchar(20),
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "estudiante" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cedula" varchar(15),
  "nombre" varchar(100),
  "apellido" varchar(100),
  "sexo" varchar(10),
  "fecha_nacimiento" date,
  "lugar_nacimiento" varchar(20),
  "parroquia_id" bigint,
  "estado_id" bigint,
  "brigada_docente_fecha_id" bigint,
  "cantidad_hermanos" int,
  "representante_id" varchar(20),
  "nombre_madre" varchar(100),
  "cedula_madre" varchar(20),
  "telefono_madre" varchar(20),
  "nombre_padre" varchar(100),
  "cedula_padre" varchar(20),
  "telefono_padre" varchar(20),
  "vive_con_madre" boolean,
  "vive_con_padre" boolean,
  "vive_con_ambos" boolean,
  "vive_con_representante" boolean,
  "rol_representante" varchar(50),
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "grado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50),
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "seccion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "docente_id" bigint,
  "grado_id" bigint,
  "seccion" varchar(2),
  "periodo" varchar(20),
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "matricula" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" bigint,
  "seccion_id" bigint,
  "brigada_docente_fecha_id" bigint,
  "fecha_inscripcion" date,
  "repitiente" boolean,
  "talla_camisa" varchar(10),
  "talla_pantalon" varchar(10),
  "talla_zapatos" varchar(10),
  "peso" float,
  "estatura" float,
  "enfermedades" varchar(100),
  "observaciones" varchar(100),
  "acta_nacimiento_check" boolean,
  "tarjeta_vacunas_check" boolean,
  "fotos_estudiante_check" boolean,
  "fotos_representante_check" boolean,
  "copia_cedula_representante_check" boolean,
  "rif_representante_check" boolean,
  "copia_cedula_autorizados_check" boolean,
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "notas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "matricula_id" bigint,
  "nota" decimal(5,2),
  "periodo" varchar(20),
  "materia" varchar(50),
  "fecha_registro" date,
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "usuario" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_usuario" varchar(50) UNIQUE,
  "email" varchar(100),
  "contrasena" varchar(255),
  "permiso_id" bigint,
  "token_acceso" varchar(500),
  "token_actualizacion" varchar(500),
  "expiracion_token" timestamp,
  "token_verificacion_email" varchar(255),
  "email_verificado" boolean,
  "token_reseteo_contrasena" varchar(255),
  "expiracion_reseteo_contrasena" timestamp,
  "pregunta_seguridad" text,
  "respuesta_seguridad" text,
  "ultimo_acceso" timestamp,
  "activo" boolean,
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp,
  "personal_id" bigint
);

CREATE TABLE "asistencia" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date,
  "seccion_id" bigint,
  "observaciones" text,
  "fecha_creacion" timestamp,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "detalle_asistencia" (
  "asistencia_id" bigint,
  "estudiante_id" bigint,
  "presente" boolean
);

-- Claves foráneas
ALTER TABLE "estado" ADD FOREIGN KEY ("pais_id") REFERENCES "pais" ("id");

ALTER TABLE "municipio" ADD FOREIGN KEY ("estado_id") REFERENCES "estado" ("id");

ALTER TABLE "parroquia" ADD FOREIGN KEY ("municipio_id") REFERENCES "municipio" ("id");

ALTER TABLE "personal" ADD FOREIGN KEY ("rol_id") REFERENCES "rol" ("id");

ALTER TABLE "personal" ADD FOREIGN KEY ("parroquia_id") REFERENCES "parroquia" ("id");

ALTER TABLE "brigada_docente_fecha" ADD FOREIGN KEY ("brigada_id") REFERENCES "brigada" ("id");

ALTER TABLE "brigada_docente_fecha" ADD FOREIGN KEY ("personal_id") REFERENCES "personal" ("id");

ALTER TABLE "estudiante" ADD FOREIGN KEY ("parroquia_id") REFERENCES "parroquia" ("id");

ALTER TABLE "estudiante" ADD FOREIGN KEY ("estado_id") REFERENCES "estado_estudiante" ("id");

ALTER TABLE "estudiante" ADD FOREIGN KEY ("brigada_docente_fecha_id") REFERENCES "brigada_docente_fecha" ("id");

ALTER TABLE "estudiante" ADD FOREIGN KEY ("representante_id") REFERENCES "representante" ("cedula");

ALTER TABLE "seccion" ADD FOREIGN KEY ("docente_id") REFERENCES "personal" ("id");

ALTER TABLE "seccion" ADD FOREIGN KEY ("grado_id") REFERENCES "grado" ("id");

ALTER TABLE "matricula" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiante" ("id");

ALTER TABLE "matricula" ADD FOREIGN KEY ("seccion_id") REFERENCES "seccion" ("id");

ALTER TABLE "matricula" ADD FOREIGN KEY ("brigada_docente_fecha_id") REFERENCES "brigada_docente_fecha" ("id");

ALTER TABLE "notas" ADD FOREIGN KEY ("matricula_id") REFERENCES "matricula" ("id");

ALTER TABLE "usuario" ADD FOREIGN KEY ("permiso_id") REFERENCES "permisos" ("id");

ALTER TABLE "usuario" ADD FOREIGN KEY ("personal_id") REFERENCES "personal" ("id");

ALTER TABLE "asistencia" ADD FOREIGN KEY ("seccion_id") REFERENCES "seccion" ("id");

ALTER TABLE "detalle_asistencia" ADD FOREIGN KEY ("asistencia_id") REFERENCES "asistencia" ("id");

ALTER TABLE "detalle_asistencia" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiante" ("id");
