CREATE TABLE "country" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "state" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "countryID" bigint,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "municipality" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "stateID" bigint,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "parish" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "minicipalityID" bigint,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "rol" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "permisos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50),
  "descripcion" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "personal" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ci" varchar(20) UNIQUE,
  "name" varchar(100),
  "lastName" varchar(100),
  "idRole" bigint,
  "telephoneNumber" varchar(20),
  "email" varchar(100),
  "birthday" timestamp,
  "direction" varchar(30),
  "parish" bigint,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "status_student" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(100),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "brigade" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "brigadeTeacherDate" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brigadeID" bigint,
  "dateI" date,
  "personalID" bigint,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "representative" (
  "ci" varchar(20) UNIQUE PRIMARY KEY,
  "name" varchar(100),
  "lastName" varchar(100),
  "telephoneNumber" varchar(20),
  "email" varchar(100),
  "maritalStat" varchar(20),
  "profesion" varchar(100),
  "birthday" timestamp,
  "telephoneHouse" varchar(20),
  "roomAdress" varchar(50),
  "workPlace" varchar(50),
  "jobNumber" varchar(20),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "student" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ci" varchar(15),
  "name" varchar(100),
  "lastName" varchar(100),
  "sex" varchar(10),
  "birthday" date,
  "placeBirth" varchar(20),
  "parishID" bigint,
  "status_id" bigint,
  -- Eliminado brigadeTeacherDateID de aquí
  "quantityBrothers" int,
  "representativeID" varchar(20),
  "motherName" varchar(100),
  "motherCi" varchar(20),
  "motherTelephone" varchar(20),
  "fatherName" varchar(100),
  "fatherCi" varchar(20),
  "fatherTelephone" varchar(20),
  "livesMother" boolean,
  "livesFather" boolean,
  "livesBoth" boolean,
  "livesRepresentative" boolean,
  "rolRopresentative" varchar(50),
  "created_at" timestamp,
  "updated_at" timestamp
);

-- Nueva tabla intermedia para la relación muchos a muchos entre student y brigade
CREATE TABLE "studentBrigade" (
  "studentID" BIGINT,
  "brigadeID" BIGINT,
  "assignmentDate" date, -- Puedes añadir la fecha de asignación a la brigada
  "created_at" timestamp,
  "updated_at" timestamp,
  PRIMARY KEY ("studentID", "brigadeID") -- Clave primaria compuesta
);

CREATE TABLE "grade" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "section" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teacherCI" bigint,
  "gradeID" bigint,
  "seccion" varchar(2),
  "period" varchar(20),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "enrollment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "studentID" bigint,
  "sectionID" bigint,
  "brigadeTeacherDateID" bigint,
  "registrationDate" date,
  "repeater" boolean,
  "chemiseSize" varchar(10),
  "pantsSize" varchar(10),
  "shoesSize" varchar(10),
  "weight" float,
  "stature" float,
  "diseases" varchar(100),
  "observation" varchar(100),
  "birthCertificateCheck" boolean,
  "vaccinationCardCheck" boolean,
  "studentPhotosCheck" boolean,
  "representativePhotosCheck" boolean,
  "representativeCopyIDCheck" boolean,
  "representativeRIFCheck" boolean,
  "autorizedCopyIDCheck" boolean,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "notes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "enrollmentID" bigint,
  "notes" decimal(5,2),
  "period" varchar(20),
  "subject" varchar(50),
  "registrationDate" date,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "usuario" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE,
  "email" varchar(100),
  "password" varchar(255),
  "permiso_id" bigint,
  "access_token" varchar(500),
  "refresh_token" varchar(500),
  "token_expiry" timestamp,
  "email_verification_token" varchar(255),
  "email_verified" boolean,
  "password_reset_token" varchar(255),
  "password_reset_expires" timestamp,
  "security_word" text,
  "respuesta_de_seguridad" text,
  "last_login" timestamp,
  "is_active" boolean,
  "created_at" timestamp,
  "updated_at" timestamp,
  "personal_id" bigint
);

CREATE TABLE "attendance" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date_a" date,
  "sectionID" bigint,
  "observaciones" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "attendanceDetails" (
  "attendanceID" bigint,
  "studentID" bigint,
  "assistant" boolean
);

ALTER TABLE "state" ADD FOREIGN KEY ("countryID") REFERENCES "country" ("id");

ALTER TABLE "municipality" ADD FOREIGN KEY ("stateID") REFERENCES "state" ("id");

ALTER TABLE "parish" ADD FOREIGN KEY ("minicipalityID") REFERENCES "municipality" ("id");

ALTER TABLE "personal" ADD FOREIGN KEY ("idRole") REFERENCES "rol" ("id");

ALTER TABLE "personal" ADD FOREIGN KEY ("parish") REFERENCES "parish" ("id");

ALTER TABLE "brigadeTeacherDate" ADD FOREIGN KEY ("brigadeID") REFERENCES "brigade" ("id");

ALTER TABLE "brigadeTeacherDate" ADD FOREIGN KEY ("personalID") REFERENCES "personal" ("id");

ALTER TABLE "student" ADD FOREIGN KEY ("parishID") REFERENCES "parish" ("id");

ALTER TABLE "student" ADD FOREIGN KEY ("status_id") REFERENCES "status_student" ("id");

-- Eliminada la clave foránea anterior de student a brigadeTeacherDateID
-- ALTER TABLE "student" ADD FOREIGN KEY ("brigadeTeacherDateID") REFERENCES "brigadeTeacherDate" ("id");

ALTER TABLE "student" ADD FOREIGN KEY ("representativeID") REFERENCES "representative" ("ci");

-- Nuevas claves foráneas para la tabla studentBrigade
ALTER TABLE "studentBrigade" ADD FOREIGN KEY ("studentID") REFERENCES "student" ("id");
ALTER TABLE "studentBrigade" ADD FOREIGN KEY ("brigadeID") REFERENCES "brigade" ("id");

ALTER TABLE "section" ADD FOREIGN KEY ("teacherCI") REFERENCES "personal" ("id");

ALTER TABLE "section" ADD FOREIGN KEY ("gradeID") REFERENCES "grade" ("id");

ALTER TABLE "enrollment" ADD FOREIGN KEY ("studentID") REFERENCES "student" ("id");

ALTER TABLE "enrollment" ADD FOREIGN KEY ("sectionID") REFERENCES "section" ("id");

ALTER TABLE "enrollment" ADD FOREIGN KEY ("brigadeTeacherDateID") REFERENCES "brigadeTeacherDate" ("id");

ALTER TABLE "notes" ADD FOREIGN KEY ("enrollmentID") REFERENCES "enrollment" ("id");

ALTER TABLE "usuario" ADD FOREIGN KEY ("permiso_id") REFERENCES "permisos" ("id");

ALTER TABLE "usuario" ADD FOREIGN KEY ("personal_id") REFERENCES "personal" ("id");

ALTER TABLE "attendance" ADD FOREIGN KEY ("sectionID") REFERENCES "section" ("id");

ALTER TABLE "attendanceDetails" ADD FOREIGN KEY ("attendanceID") REFERENCES "attendance" ("id");

ALTER TABLE "attendanceDetails" ADD FOREIGN KEY ("studentID") REFERENCES "student" ("id");